## Numpy Exercises

Import the numpy package under the name np

In [1]:
import numpy as np

Print the numpy version and the configuration

In [5]:
print(np.__version__)
print(np.show_config())

1.24.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

Create a null vector of size 10 

In [16]:
arr = np.empty((2,5))
arr.size

10

How to find the memory size of any array 

In [8]:
arr = np.array([1,2,3,4,5])
memory_size = arr.size * arr.itemsize
memory_size

20

How to get the documentation of the numpy add function from the command line?

In [9]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

Create a null vector of size 10 but the fifth value which is 1

In [2]:
arr = np.zeros(10)

# setting the fifth value to one
arr[4] = 1

arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

 Create a vector with values ranging from 10 to 49

In [5]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Reverse a vector (first element becomes last)

In [ ]:
arr = np.array([1,2,3,4,5,6])
# reversing the vector
reversed = arr[::-1]
reversed

Create a 3x3 matrix with values ranging from 0 to 8 

In [17]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements from [1,2,0,0,4,0]

In [28]:
arr = np.array([1,2,0,0,4,0])
indices = np.where(arr!=0)[0]
indices

array([0, 1, 4], dtype=int64)

Create a 3x3 identity matrix

In [33]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values

In [36]:
arr = np.random.rand(3,3,3)
arr

array([[[0.78302523, 0.2848318 , 0.57507438],
        [0.84590911, 0.39588846, 0.99880627],
        [0.23983545, 0.06575462, 0.77103745]],

       [[0.57859648, 0.76868366, 0.04227551],
        [0.24853133, 0.38239313, 0.04191378],
        [0.49553734, 0.35739293, 0.47058691]],

       [[0.83991504, 0.33645032, 0.16509739],
        [0.32911462, 0.03134146, 0.83784179],
        [0.22225706, 0.40448362, 0.7879769 ]]])

Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
arr = np.random.rand(10,10)
mini_value = arr.min()
max_value = arr.max()

print("the minimum value is",mini_value)
print("the maximum value is", max_value)

the minimum value is 0.005227704024004298
the maximum value is 0.9901233295572989


Create a random vector of size 30 and find the mean value

In [48]:
arr = np.random.rand(3,10)
arr.mean()    #finding the mean

0.6185363373115933

 Create a 2d array with 1 on the border and 0 inside

In [56]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

How to add a border (filled with 0's) around an existing array?

In [68]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
rows,cols = arr.shape
border_zeros = np.zeros((rows+2,cols+2))
border_zeros[1:-1,1:-1] = arr
border_zeros

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 4., 5., 6., 0.],
       [0., 7., 8., 9., 0.],
       [0., 0., 0., 0., 0.]])

What is the result of the following expression?

In [69]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [73]:
arr = np.diag([1,2,3,4], k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Create a 8x8 matrix and fill it with a checkerboard pattern 

In [84]:
arr = np.zeros((8,8))

# alternating the rows and columns
arr[1::2,::2] = 1
arr[::2,1::2] = 1

arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [95]:
shape = (6,7,8)
index_term = 100

# creating an empty array with the shape given
arr = np.empty(shape)

# finding the (x,y,z) of the 100th element
index_value = np.unravel_index(index_term , shape)
index_value

(1, 5, 4)

 Create a checkerboard 8x8 matrix using the tile function

In [98]:
#  creating 2x2 checkerboard
arr = np.array([[0,1],[1,0]])
# using the tile method to create 8x8 pattern
matrix = np.tile(arr, (4,4))

matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

 Normalize a 5x5 random matrix

In [108]:
arr = np.random.random((5,5))
mean_arr = arr.mean()
std_arr = arr.std()
normalized = (arr - mean_arr)/ std_arr
normalized

array([[-0.48683006,  0.28202903,  0.82813617, -0.08573137, -0.41690059],
       [-0.03863237,  1.03006626,  0.87232108,  1.73881121, -1.41859026],
       [ 1.23756413,  1.0178432 ,  1.03491635, -0.05139502, -0.52108226],
       [-1.76691882,  0.50436263, -0.64868195, -1.03489738, -0.71374811],
       [ 1.53207064, -1.31502503,  0.48757297, -0.25398209, -1.81327839]])